### ISSUE TITLE
Move dark/light mode toggle to navbar and style :)

### ISSUE THREAD

**Issue by JulieKnox225** [JulieKnox225/BVT-Alumni-Tracker-Object-Oriented-Otters#20]
Just so it matches the figma design :)

**Comment by AndyBuddy** [comment]
Light mode toggle is now like the figma design. The dropdown still needs to be a hamburger, I can tackle that next



![Image](https://github.com/JulieKnox225/BVT-Alumni-Tracker-Object-Oriented-Otters/assets/114187210/6896c690-35d9-4074-8372-ad600d3f304c)
