### ISSUE TITLE
bugfix: profile icons on home page are too large

### ISSUE THREAD

**Issue by JulieKnox225** [JulieKnox225/BVT-Alumni-Tracker-Object-Oriented-Otters#31]
![Screenshot (6)](https://github.com/JulieKnox225/BVT-Alumni-Tracker-Object-Oriented-Otters/assets/107340095/049c3c7f-7922-49a8-99b5-05b80b267c79)

**Comment by AndyBuddy** [comment]
It shouldn't go passed the footer now. *This page is not done yet
